name: media-system

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GATEWAY_INTERNAL_URL: http://api-gateway:4000
        NEXT_PUBLIC_APP_HOST_IP: ${PUBLIC_HOST:-localhost}
        NEXT_PUBLIC_GATEWAY_URL: http://localhost:4000
        NEXT_PUBLIC_API_URL: http://localhost:4000
        NEXT_PUBLIC_AVATAR_STORAGE_URL: http://${PUBLIC_HOST:-localhost}:19000
        NEXT_PUBLIC_MEDIA_STORAGE_URL: http://${PUBLIC_HOST:-localhost}:19000
    image: media-system-frontend:local
    container_name: frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      GATEWAY_INTERNAL_URL: http://api-gateway:4000
      NEXT_PUBLIC_GATEWAY_URL: http://localhost:4000
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXT_PUBLIC_AVATAR_STORAGE_URL: http://${PUBLIC_HOST:-localhost}:19000
      NEXT_PUBLIC_MEDIA_STORAGE_URL: http://${PUBLIC_HOST:-localhost}:19000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
